### ISSUE TITLE
optimal output in usl mode incorrect?

### ISSUE THREAD

**Issue by mcm1956** [smoeding/usl#7] opened 2020-10-30 20:52 UTC
I am using the usl and am unsure if the following output is a bug or I am just misunderstanding it.
my data:
 Pods Thruput
1    1      60
2    2     120
3    4     220
4    8     400
5   12     440
6   16     490

model summary:
Call:
usl(formula = Thruput ~ Pods, data = sib1)

Efficiency:
   Min     1Q Median     3Q    Max 
0.4990 0.6518 0.8554 0.9573 0.9776 

Residuals:
     Min       1Q   Median       3Q      Max 
-19.1582  -5.8957  -0.8903   5.7664  17.9032 

Coefficients:
        Estimate  Std. Error  t value  Pr(>|t|)    
alpha   0.012318    0.030875    0.399   0.71663    
beta    0.003549    0.001327    2.674   0.07545  . 
gamma  61.372822    6.680004    9.188   0.00273  **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 16.39 on 3 degrees of freedom

Scalability bounds:
limit: Thruput 4982 (Amdahl asymptote)
peak:  Thruput 482.6 at Pods 16.68 
opt:_   Thruput 198.6 at Pods 81.18
as you can see, the optimal is way past the peak AND if I add some predictive data it is way out past the point of retrograde performance.  Since I am just beginning to use this it is most probably that I am misinterpreting something

here's the plot with X set to a max of 128:
![image](https://user-images.githubusercontent.com/37347047/97755748-59a51980-1abf-11eb-82bc-11aa47361f47.png)
generated with:
plot(sib1,pch=16,col="blue",xlim=c(0,max(128)))
plot(sib1.model, col="red", add=TRUE, bounds=TRUE)

**Comment by smoeding** [comment] 2020-10-31 09:54
The term _optimal scalability_ was coined bei Neil Gunther and may not match your expectation. It has more of a theoretical value. I wrote a little script with your data:

```R
library(usl)

sib1 <- read.table(text="Pods Thruput
1 60
2 120
4 220
8 400
12 440
16 490
", header=TRUE)

sib1 <- read.table(file="~/data.txt", header=T)

u <- usl(Thruput ~ Pods, sib1)

summary(u)

plot(sib1, pch=16, col="blue", xlim=c(0,128), ylim=c(0,5000))
plot(u, add=T, bounds=T)

plot(scalability(u), add=T, xlim=c(0,120), col="blue")
plot(scalability(u, beta=0), add=T, xlim=c(0,120), col="green")

# predict Thruput for some number of Pods with current scalability
predict(u, data.frame(Pods = c(20, 40, 60, 80, 100)))

# predict Thruput for some number of Pods without coherency penalty
predict(u, data.frame(Pods = c(20, 40, 60, 80, 100)), beta=0)
```

The plot has a different scale to show the point. The summary ouput shows Amdahl's asymptote as 4982. This is indicated by the top dotted line. It's the limit for your alpha if beta would be zero.

Then we have the dotted line going from the origin right and upwards. This line indicates linear scalability which you would see if alpha and beta would be zero. In your data one Pod has a Throughput of 60 and two Pods reach 120; that's linear. Unfortunately it doesn't go on like that. But this line shows how it would look.

Optimal scalability (according to Neil Gunther) is given by the intersection of these two lines. But this doesn't mean your system (where alpha>0 and beta>0) can reach this point. If you look into the documentation page for the `optimal.scalability` function you can see the formula how it is calculated (1/alpha). So with beta>0 you will never reach this.

Your point seems to be that Nopt is higher than Npeak. Yes, this looks wrong at first sight, but it all comes from your data.

Your alpha is pretty good: about 1.2% where other systems reach 2-3% at most. So this means your system has a better way of working in parallel than most other systems. There is only a minor overhead of work that can't be done in parallel.

But your beta is much worse than most other systems and that's causing the limits you see in the model. Your system needs some point-to-point communication (cache-validate, message passing, ...) and this drags scalability down for each additional Pod you add.

The plot shows your data (blue dots) and the calculated scalability function (blue line) going up to 120 Pods. As you can see the peak is pretty obvious. Using more than 16 Pods reduces Throughput according to the model. And this is mostly caused by your beta.

The green line shows the expected scalability if beta would be zero. So depending on what you can do to improve your beta you will see your scalability to be somewhere in between. 

You are using the number of Pods for your model. Are you looking at a Kubernetes system here? If yes: is a single Pod really working on it's own or is there some sort of communication between the Pod and other nodes (controllers?, masters?). I don't know anything about Kubernetes but if a single Pod already does some sort of synchronization then your baseline already includes some penalties that the model is not aware of.

Does this make sense to you?

**Comment by mcm1956** [comment] 2020-10-31 11:54
Thanks so much.  Yes, it all makes sense and I appreciate your response.  And yes, it is a kubernetes/openshift system and it is about as klunky as it gets.  But itndoes have a very high nifty factor (HNF) so it proved irresistible to architects.

Thanks again!

Mark Monaghan

303-601-5152

Semper Paratus

**Comment by mcm1956** [comment] 2020-10-31 12:42
Btw, thanks for creating this package.  It is so much easier than the old method I was using with Excel.

Mark Monaghan

303-601-5152

Semper Paratus

**Comment by smoeding** [comment] 2021-02-20 12:05
Closing this now as it really is not an issue.

**Closed as completed by smoeding** 2021-02-20 12:05 UTC
